Melhorias registro de conteúdos
portabilis/i-diario pull request #126
Opened 2023-01-17 19:20 UTC by marcosoliveirasoares94

Closes https://github.com/portabilis/i-diario/issues/119

Possibilita criar mais de um conteúdo para o mesmo dia, caso o parâmetro esteja ativo em Administrativo > Configurações gerais, ele passa a validar as aulas e não o dia.

Ao desabilitar o parâmetro, a validação volta a ser por dia/disciplina e as colunas de aula não aparecerão.

Para ativar o parâmetro:

`url/configuracoes-gerais/editar`

No checkbox:

![config](https://user-images.githubusercontent.com/52477784/209016238-53e7780e-bf3f-4c57-ac01-a69f54065e6f.png)

Após ativar o check acima, na listagem dos registros já irá aparecer o número de aula na listagem.

![listagem](https://user-images.githubusercontent.com/52477784/209016391-a3a83e04-fcf5-4355-a2f3-ff3e715cadc8.png)

Ao entrar pra criar um registro, aparecerá o campo para selecionar a aula.

![criacao](https://user-images.githubusercontent.com/52477784/209016685-f1c140d6-8753-401d-b5dd-312c41a9d80c.png)

![criacao2](https://user-images.githubusercontent.com/52477784/209017255-eab28571-e2a8-4024-80f4-61a10c8211b9.png)

Neste exemplo, ao selecionar as 3 aulas, a criação irá triplicar os conteúdos e criar para as 3 aulas.

![criado](https://user-images.githubusercontent.com/52477784/209017464-762a5a58-73fe-4379-954c-306b748abc2f.png)

Caso haja alguma aula utilizada, irá retornar a mensagem de erro dizendo que a aula está em uso.

Ao visualizar um conteúdo criado, o campo aula deverá ficar desabilitado:

![visualizando](https://user-images.githubusercontent.com/52477784/209018264-55e1496f-4dc7-401a-b9d6-1dd4406cc33f.png)

Ao editar, a aula também não poderá ser ajustada, apenas os conteúdos:

![edicao](https://user-images.githubusercontent.com/52477784/209018535-7edccd6f-43a7-4b02-b7f3-7598cb03a6f9.png)

**IMPORTANTE**
- Caso o checkbox não seja habilitado, o sistema não tem impacto algum, continuará funcionando normalmente.

2023-02-13 18:50 UTC, edersoares commented
@marcosoliveirasoares94 obrigado pela contribuição, vamos fazer as análises internas de compatibilidade e retornamos ;)

2023-03-02 02:46 UTC, marcosoliveirasoares94 commented
> @marcosoliveirasoares94 obrigado pela contribuição, vamos fazer as análises internas de compatibilidade e retornamos ;)

@edersoares, complementando este PR com esse novo PR https://github.com/portabilis/i-diario/pull/128

2023-05-03 17:05 UTC, edersoares requested changes
@marcosoliveirasoares94 @gustavomendess muito obrigado pela contribuição!

Desculpem a demora, estaremos adicionando no nosso fluxo de qualidade para aprovarmos o merge ;)

2023-05-03 17:05 UTC, edersoares commented on app/views/discipline_content_records/index.html.erb
> +          <td id="pagination-tfoot" colspan="6">
Colspan vai depender se a `@allow_class_number` for `true`

2023-05-03 17:05 UTC, edersoares commented on db/migrate/20221220165443_add_class_number_to_content_record.rb
> +    add_column :content_records, :class_number, :integer, default: 0
A coluna pode ser nullable e `nil` ser o default

2023-05-03 17:05 UTC, edersoares commented on script/start
> +  bundle exec rake entity:admin:create NAME=prefeitura ADMIN_PASSWORD=A123456789$
Não faz sentido mudar isso neste PR ;)

2023-12-12 17:02 UTC, msoares94 commented
@edersoares  e @gustavomendess algum retorno sobre essa melhoria proposta pela comunidade, ela está a bastante tempo aguardando reintegração e é algo muito útil e parametrizável?

O ingresso dessa funcionalidade estimula a contribuição por parte da comunidade, pois sabemos que nossas propostas são aceitas.

2023-12-26 15:01 UTC, edersoares commented
@msoares94 @gustavomendess eu precisei atualizar esta branch para retomarmos essa melhoria, conseguem validá-la novamente por favor?

Principalmente este trecho https://github.com/portabilis/i-diario/pull/126/files#diff-931228249692a941a48c22abe2b692ed5d6cdd4729f053fd78ea63b93485034cR81-R89.

2024-06-19 19:19 UTC, edersoares commented
Já aceito o PR https://github.com/msoares94/i-diario/pull/1.

2024-06-19 19:19 UTC, closed without merging